theme = "monokai_pro_ristretto"

[keys.normal]
tab = "command_mode"
A-P = "command_palette"
"space" = { "space" = "command_mode", c = ":buffer-close", t = ":write", q = ":quit" }
"C-/" = "toggle_comments"
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
"," = { "," = "normal_mode",  w = ":write"  }
"C-/" = "toggle_comments"

[editor]
indent-guides.render = true
cursorline = true
color-modes = true
line-number = "relative"
bufferline = "always"
auto-save = true

[editor.statusline]
left = ["mode", "spacer", "spinner"]
center = ["file-name", "diagnostics",]
right = [ "selections", "position", "spacer", "position-percentage", "spacer", "file-type"]

[editor.whitespace]
# render = { newline = "all" }

[editor.lsp]
display-messages = true
