[[language]]
name = "python"
auto-format = true
language-servers = [ "pyright", "ruff" ]
formatter = { command = "ruff", args = ["format"]}

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"


[[language]]
name = "rst"
language-servers = [ "esbonio" ]

[language-server.esbonio]
command = "esbonio"
