theme = "starlight"

[keys.normal]
tab = "command_mode"
A-P = "command_palette"
"space" = { "space" = "command_mode", c = ":buffer-close", t = ":write", T = ":write-all", q = ":quit" }
"C-/" = "toggle_comments"
"C-i" = "jump_forward"
"A-g" = ":reset-diff-change"
"C-r" = ":reload-all"
h = "goto_word"
X = "select_line_above"
x = "select_line_below"

[keys.insert]
"C-/" = "toggle_comments"
"C-w" = "no_op"
"C-h" = "no_op"
"C-k" = "no_op"
"C-d" = "no_op"
"C-j" = "no_op"
"A-d" = "no_op"

[editor]
rulers = [80, 120]
cursorline = true
color-modes = true
completion-replace = true
bufferline = "always"
auto-save = true
jump-label-alphabet = "eirsaotndhfuywgmplc,x.vkbjz/"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = [ "version-control", "spacer", "selections", "position", "spacer", "position-percentage", "spacer", "file-type"]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

